jointnames = {0: "Head",
              1: "ShoulderSpine",
              2: "LeftShoulder",
              3: "LeftElbow",
              4: "LeftHand",
              5: "RightShoulder",
              6: "RightElbow",
              7: "RightHand",
              8: "MidSpine",
              9: "BaseSpine",
              10: "LeftHip",
              11: "LeftKnee",
              12: "LeftFoot",
              13: "RightHip",
              14: "RightKnee",
              15: "RightFoot",
              16: "LeftWrist",
              17: "RightWrist",
              18: "Neck",
              19: "Unknown"}

